name: my_health_care
description: Health Care Flutter application.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: 0.5.12
  firebase_analytics: 1.0.1
  firebase_database: 1.0.1



flutter:

  uses-material-design: true
  assets:
    - images/app_home.jpg
    - images/red_cross.png
    - images/drawer.jpg
    - images/banner.jpg
  fonts:
    - family: IBMPlexSerif
      fonts:
        - asset: fonts/IBMPlexSerif-Bold.ttf
        - asset: fonts/IBMPlexSerif-Regular.ttf
        - asset: fonts/IBMPlexSerif-SemiBold.ttf
