name: my_health_care
description: Health Care Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_auth: 0.5.12
  firebase_analytics: 1.0.1
  firebase_database: 1.0.1


flutter:

  uses-material-design: true
  assets:
    - images/app_home.jpg
    - images/red_cross.png
  fonts:
    - family: IBMPlexSerif
      fonts:
        - asset: fonts/IBMPlexSerif-Bold.ttf
        - asset: fonts/IBMPlexSerif-Regular.ttf
        - asset: fonts/IBMPlexSerif-SemiBold.ttf
